export const usePortfolioStore = defineStore('PortfolioStore', () => {
  const basic = ref({
    name: 'Tareq Abdelwhap',
    me: '/images/me.png',
    role: 'Full Stack Web Developer',
    description: `I'm a dedicated web developer with a burning desire to create innovative
        applications that make a positive impact on people's lives. My journey
        began +4 years ago when I first discovered the power of coding and its
        potential to transform the world.`,
  });

  const skills = ref([
    {
      name: 'Front End',
      skills: [
        {
          name: 'HTML',
          color: 'text-red-500',
          bgColor: 'bg-red-900',
          borderColor: 'border-red-900',
          icon: 'logos:html-5',
          years: '+5 years',
          new: false,
          show: true,
        },
        {
          name: 'CSS',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:css-3',
          years: '+5 years',
          new: false,
          show: true,
        },
        {
          name: 'Tailwind',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:tailwindcss-icon',
          years: '+1 years',
          new: false,
          show: true,
        },
        {
          name: 'Javascript',
          color: 'text-yellow-500',
          bgColor: 'bg-yellow-900',
          borderColor: 'border-yellow-500',
          icon: 'logos:javascript',
          years: '+5 years',
          new: false,
          show: true,
        },
        {
          name: 'jQuery',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'devicon:jquery',
          years: '+5 years',
          new: false,
          show: true,
        },
        {
          name: 'Vue3',
          color: 'text-green-500',
          bgColor: 'bg-green-900',
          borderColor: 'border-green-900',
          icon: 'logos:vue',
          years: '+4 years',
          new: false,
          show: true,
        },
        {
          name: 'Nuxt3',
          color: 'text-green-500',
          bgColor: 'bg-green-900',
          borderColor: 'border-green-900',
          icon: 'logos:nuxt-icon',
          years: '+1 years',
          new: false,
          show: true,
        },
        {
          name: 'Ionic Vue',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:ionic-icon',
          years: '+1 years',
          new: false,
          show: true,
        },
        {
          name: 'Pinia',
          color: 'text-yellow-500',
          bgColor: 'bg-yellow-900',
          borderColor: 'border-yellow-500',
          icon: 'logos:pinia',
          years: '+3 years',
          new: false,
          show: true,
        },
        {
          name: 'Typescript',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:typescript-icon',
          years: '+1 years',
          new: false,
          show: true,
        },

        {
          name: 'Ajax',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:ajax',
          years: '+5 years',
          new: false,
          show: false,
        },
      ],
    },
    {
      name: 'Back End',
      skills: [
        {
          name: 'PHP',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:php',
          years: '+5 years',
          new: false,
          show: true,
        },
        {
          name: 'Laravel',
          color: 'text-red-500',
          bgColor: 'bg-red-900',
          borderColor: 'border-red-900',
          icon: 'logos:laravel',
          years: '+4 years',
          new: false,
          show: true,
        },
        {
          name: 'MySQL',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:mysql',
          years: '+4 years',
          new: false,
          show: true,
        },
        {
          name: 'Redis',
          color: 'text-red-500',
          bgColor: 'bg-red-900',
          borderColor: 'border-red-900',
          icon: 'logos:redis',
          years: '+1 months',
          new: false,
          show: false,
        },

        {
          name: 'NodeJS',
          color: 'text-green-500',
          bgColor: 'bg-green-900',
          borderColor: 'border-green-900',
          icon: 'logos:nodejs-icon',
          years: '+1 months',
          new: true,
          show: true,
        },
        {
          name: 'Express',
          color: 'text-black',
          bgColor: 'bg-black',
          borderColor: 'border-black',
          icon: 'devicon:express',
          years: '+1 months',
          new: true,
          show: true,
        },
        {
          name: 'MongoDB',
          color: 'text-green-500',
          bgColor: 'bg-green-900',
          borderColor: 'border-green-900',
          icon: 'logos:mongodb-icon',
          years: '+1 months',
          new: true,
          show: true,
        },
      ],
    },

    {
      name: 'Other',
      skills: [
        {
          name: 'Git',
          color: 'text-orange-500',
          bgColor: 'bg-orange-900',
          borderColor: 'border-orange-900',
          icon: 'logos:git-icon',
          years: '+3 years',
          new: false,
          show: true,
        },
        {
          name: 'Bitbucket',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: 'logos:bitbucket',
          years: '+1 years',
          new: false,
          show: true,
        },
        {
          name: 'OOP',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: '',
          years: '+3 years',
          new: false,
          show: true,
        },
        {
          name: 'SOLID',
          color: 'text-blue-500',
          bgColor: 'bg-blue-900',
          borderColor: 'border-blue-900',
          icon: '',
          years: '+3 years',
          new: false,
          show: true,
        },
      ],
    },
  ]);

  const findSkill = (skillsArray: string[]) => {
    return skills.value
      .flatMap(skill => skill.skills)
      .filter(skill =>
        skillsArray
          .map(arr => arr.toLowerCase())
          .includes(skill.name.toLowerCase())
      );
  };

  const experiences = ref([
    {
      position: 'Warehouse Manager',
      company: 'Milano Export and Import',
      tags: ['Cairo, Egypt', 'Full-Time', 'On-Site'],
      date: ['2017', '2019'],
      responsibilities: [
        'Warehouse Manager',
        'I developed a small system to facilitate warehouse management and sold it to the company when I resigned.',
      ],
      skills: findSkill([
        'HTML',
        'CSS',
        'Javascript',
        'Ajax',
        'MySQL',
        'jQuery',
        'PHP',
      ]),
    },
    {
      position: 'Personal Goal Pursuit',
      company: 'Career Break',
      tags: ['Cairo'],
      date: ['2019', '2020'],
      responsibilities: [
        'I was on a break because I was attending a full-stack diploma program at the Russian Cultural Center.',
      ],
      skills: findSkill([]),
    },
    {
      position: 'Full-Stack Developer',
      company: 'Al-Tarek and Islam Auto',
      tags: ['Cairo, Egypt', 'Full-Time', 'Hybird'],
      date: ['2020', '2023'],
      responsibilities: [
        'Designed and developed a full ERP system, streamlining business processes and increasing efficiency.',
        'Developed dynamic web applications with PHP and MySQL, focusing on enhancing user engagement and optimizing performance. Proficiently mastered AJAX and Vue.js to create interactive interfaces.',
        'API integration for seamless third-party service integration.',
        "Integrated additional functionalities such as Dropzone for efficient file uploads and Chart.js for advanced data visualization and enhances the application's analytical capabilities.",
      ],
      skills: findSkill([
        'Javascript',
        'Vue3',
        'Pinia',
        'PHP',
        'Laravel',
        'MySQL',
        'Git',
        'OOP',
        'SOLID',
      ]),
    },
    {
      position: 'Full-Stack Developer',
      company: 'Real Deal EG',
      tags: ['Cairo, Egypt', 'Full-Time', 'Remote'],
      date: ['2023', 'Present'],
      responsibilities: [
        'Implementing a modular architecture with HMVC, service and repository patterns for high maintainability.',
        // 'Implemented asynchronous processing through queues and jobs, significantly boosting system performance and efficiency.',
        // 'Championing multi-language support and S3 storage for secure file management.',
        // 'Streamlined project management and task tracking by utilizing tools such as Trello and Jira.',
        'Architected scalable and maintainable front-end systems using component-based approaches with Vue.js 3 and Nuxt 3.',
        // 'Leveraged Vite for fast build processes and improved development workflows.',
        'Enhanced application performance with lazy loading, code splitting, and optimized state management using Pinia.',
        'Employed Tailwind CSS for responsive and maintainable styling.',
        'Created reusable components and libraries to enhance productivity and consistency.',
        'Improving code quality and minimizing runtime errors by implementing type-safe practices with TypeScript.',
        'Collaborated closely with UI/UX designers using Figma to deliver cohesive and user-friendly interfaces.',
      ],
      skills: findSkill([
        'Javascript',
        'Vue3',
        'Nuxt3',
        'Typescript',
        'Tailwind',
        'Laravel',
        'MySQL',
        'Redis',
        'Bitbucket',
      ]),
    },
  ]);

  return {
    basic,
    skills,
    experiences,
  };
});
